package com.test.demo06;

import com.rabbitmq.client.*;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeoutException;

/**
 * @ClassName RPCClient
 * @Author liupanpan
 * @Date 2025/11/14
 * @Description
 */
public class RPCClient {
    private Connection connection;
    private Channel channel;
    private String requestQueueName = "rpc_queue";

    public RPCClient() throws IOException, TimeoutException {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("172.16.30.21");
        factory.setUsername("rabbitmq");
        factory.setPassword("310012");

        connection = factory.newConnection();
        channel = connection.createChannel();
    }

    public static void main(String[] args) {
        try {
            RPCClient fibonacciRpc = new RPCClient();
            for (int i = 0; i < 32; i++) {
                String string = Integer.toString(i);
                String response = fibonacciRpc.call(string);
                System.out.println("got ---> "+response);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public String call(String message) throws Exception {
        final String corrId = UUID.randomUUID().toString(); // 生成一个唯一的correlationId编号并保存，目的：将rpc响应与请求连接起来

        String replyQueueName = channel.queueDeclare().getQueue();

        AMQP.BasicProperties props = new AMQP.BasicProperties.Builder()
                .correlationId(corrId)
                .replyTo(replyQueueName) // 命名回调队列
                .build();
        // 发送请求，传递给server
        channel.basicPublish("",
                requestQueueName,
                props,
                message.getBytes(StandardCharsets.UTF_8));

        final CompletableFuture<Object> response = new CompletableFuture<>();
        // 获取server返回的结果
        // ctag: the consumerTag generated by the server
        String ctag = channel.basicConsume(replyQueueName,
                true,
                (consumerTag, delivery) -> {
                    if (delivery.getProperties().getCorrelationId().equals(corrId)) { // 匹配相应的相应
                        // 如果尚未完成，则将 get() 和相关方法返回的值设置为给定值。
                        response.complete(new String(delivery.getBody(), StandardCharsets.UTF_8));
                    }
                },
                consumerTag -> {}
        );
        String result = (String) response.get();
        // 取消消费者。调用消费者的 `handleCancelOk` 方法。
        channel.basicCancel(ctag);
        return result;
    }

    public void close() throws IOException {
        connection.close();
    }
}
